name: learning_bloc_timer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.0
  flutter_bloc: ^9.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
